### ISSUE TITLE
Rutime error in `generateIndexHtml`

### ISSUE THREAD

**Issue by kunom** [TimSVector/vc_scripts_submodule#2]
Another one :-), did not notice this one on Windows:

```
Traceback (most recent call last):
  File "/tools/vcast/vc_scripts_submodule/vcast_exec.py", line 401, in <module>
    vcExec.generateIndexHtml()
  File "/tools/vcast/vc_scripts_submodule/vcast_exec.py", line 196, in generateIndexHtml
    create_index_html.run(htmlReportList)
AttributeError: 'function' object has no attribute 'run'
```

NB: Have you ever tried VS Code with its Python tooling? It probably could help you discover such and other issues: just look for wiggles (likely errors) and white text (unidentified type --> could be due to a typo):

![image](https://github.com/user-attachments/assets/48ca2150-305d-4f60-8084-2b82e9d9eb0d)

**Comment by TimSVector** [comment]
Yeah, this is a relatively new repository that’s under active development That supports three or four other repositories that needs to stay in sync with a separate repository.

So it's not surprising, but thank you.
________________________________
From: Kuno Meyer ***@***.***>
Sent: Wednesday, October 2, 2024 7:21:15 AM
To: TimSVector/vc_scripts_submodule ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TimSVector/vc_scripts_submodule] Rutime error in `generateIndexHtml` (Issue #2)


Another one :-), did not notice this one on Windows:

Traceback (most recent call last):
  File "/tools/vcast/vc_scripts_submodule/vcast_exec.py", line 401, in <module>
    vcExec.generateIndexHtml()
  File "/tools/vcast/vc_scripts_submodule/vcast_exec.py", line 196, in generateIndexHtml
    create_index_html.run(htmlReportList)
AttributeError: 'function' object has no attribute 'run'


NB: Have you ever tried VS Code with its Python tooling? It probably could help you discover other such and other issues: just look for wiggles (likely errors) and white text (unidentified type --> could be due to a typo):

image.png (view on web)<https://github.com/user-attachments/assets/48ca2150-305d-4f60-8084-2b82e9d9eb0d>

**Comment by TimSVector** [comment]
Fixed

**Comment by TimSVector** [comment]
Fixed
